### ISSUE TITLE
Recriar interface para projetos

### ISSUE THREAD

**Issue by andreaugusto-sourc** [fabsoftwareitp/sitefabrica-jig#23]
Recriar uma interface para a parte de projetos, levando em consideração os atributos: titulo do projeto, imagem ilustrativa e texto informativo. E entender as limitações da linguagem de marcação( Markdown)

# Para ajudar na lida do Markdown, deixo esse link:
https://docs.pipz.com/central-de-ajuda/learning-center/guia-basico-de-markdown#open

## E se tiver problemas com o Jigsaw, olhe na documentação do próprio ou me contate.
https://jigsaw.tighten.com/docs/content/

## Projetos

EspWeb: https://ic.itp.ifsp.edu.br/espweb/
SGE: https://ic.itp.ifsp.edu.br/sgeIFSP/
SVSA: https://svsa.itp.ifsp.edu.br/
Show de Fisica: https://showdefisica.itp.ifsp.edu.br/
Consultório na RUA: http://189.28.128.100/dab/docs/portaldab/publicacoes/manual_aplicacao_visual_consultorio_rua.pdf

**Comment by danilocbueno** [comment]
Voltada para em desenvolvimento pois faltou criar o PR (Pull-request)
