### ISSUE TITLE
Ideias para o IF Casa Aberta 23

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/sitefabrica-jig#38]
Conforme conversado em reunião, pensar em ideias de projetos para o IF Casa Aberta 23 e documentar aqui nessa issue. Pode colocar como comentários mesmo.

**Comment by ViniciusMrV** [comment]
**Faríamos a apresentação para vários visitantes (no auditório, por exemplo), ou colocaríamos placas/folders indicando onde fica a sala da Fábrica (para ter um número mais "controlado" de interessados)?**
1- Poderíamos apresentar nossa sala no IF Casa Aberta 23, que torcemos para estar expandida até 2023;
2- Podemos fazer alguma gincana envolvendo os visitantes (bom, é difícil pensar em como essa gincana funcionaria, mas dá para irmos planejando conforme o tempo);
3- Recompensa dos participantes (ou vencedores da gincana ) em forma de doce, todo mundo gosta de doces.

**Comment by CorreaJo** [comment]
Poderíamos fazer como uma partida de torta na cara, mas ao invés de ser presencial, seria virtual. 
Faríamos isso no auditório e pegando alguns como "cobaias" para que jogassem nosso joguinho de torta na cara. Ele teria botões ou algo do tipo, pra que a pessoa possa apertar e ganhar, após o jogo, nós iríamos apresentar como funciona basicamente e o que usamos para criar o jogo.

**Comment by gabs1m** [comment]
Independente do que formos fazer, temos que pensar em uma atividade relativamente curta e que envolva um número grande de pessoas, para que a maioria possa participar.

**Comment by danilocbueno** [comment]
### TechTalk15 
**ideia**: Rafalel: Palestra sobre as possibilidades que o aplicações que o desenvolvimento de software tem no mercado de trabalho (nós da fábrica); Duas salas, e indica a sala da fábrica para visitação;

**implementação**: Escolher quem e o que será apresentado.

**Comment by danilocbueno** [comment]
### Space Invaders com acelerômetro
**ideia**: criar um jogo estilo space invaders com JS usando o acelerômetro do celular para controlar o personagem. O jogo pode ser simples começando apenas com o controle via celular e pode ficar complexo utilizando multiplayer.

**implementação**: usar a api https://developer.mozilla.org/en-US/docs/Web/Events/Detecting_device_orientation. Criar o jogo em si e usar os dados do celular para controlar o game.

**Comment by danilocbueno** [comment]
### Escolha seu campeão
**ideia**: parecido com o mural do https://www.leagueoflegends.com/pt-br/champions/. O usuário tiraria uma foto e através de filtros escolheria qual estilo gostaria de colocar em sua foto, exemplos: com capacete, uma espada, um arco e mostrar as fotos em um mural.

**implementação**: talvez o mais complicado seja a parte de como colocar filtros em imagens. Precisa pesquisar sobre como isso poderia ser implementado.

**Comment by danilocbueno** [comment]
### Raio X HTML

**ideia**: Expor algum site em algum datashow. Com o celular do usuário ele apontaria para esse site e conseguiria ver o código fonte da página em seu dispositivo. 

**implementação**: Usar a API de https://developer.mozilla.org/en-US/docs/Web/API/WebXR_Device_API para mostrar no celular do usuário esse código fonte.

**Comment by danilocbueno** [comment]
### Painel de fotos

**ideia**: Um painel com uma câmera acoplada que responde ao comando de voz, tira a foto e publica na rede social automaticamente; Pode ficar mais complexo, por exemplo: Pode usar a o sintetizador de voz pra criar um background aleatório único para cada foto..

**implementação**: Usar a API de speech para reconhecer a voz do usuário; Montar um webapp para capturar a foto e enviar para as redes sociais; Fazer a comunicação com as redes sociais;

**Comment by danilocbueno** [comment]
### Fake "Twitter" da Fábrica

**ideia**: Um webapp que usa a mesa digitalizadora para "desenhar uma msg" e postar em um mural de recados que ficaria exposto em um painel no corredor do bloco de Informática. O usuário loga com sua rede social no app, cria a imagem, o webapp pega a foto do usuário na rede social, e posta juntamente com sua msg no webapp de mural.

**implementação**: usar apis de autenticação com redes sociais. Usar API de canvas para pegar desenho do usuário;

**Comment by danilocbueno** [comment]
🚀 Primeiro lugar.
Depois fazemos a classificação das demais!

**Comment by danilocbueno** [comment]
Ate a data de hoje apenas o @andreaugusto-sourc  e o @Vitor-G-Aquino votaram!

**Comment by danilocbueno** [comment]
**Resultado Final:**
1. Space Invaders com acelerômetro
2. Escolha seu campeão
3. Raio X HTML
