### ISSUE TITLE
Atualizar o certificado de segurança do servidor

### ISSUE THREAD

**Issue by danilocbueno** [fabsoftwareitp/sitefabrica-jig#47]

**Comment by Vitor-G-Aquino** [comment]
Certificados HTTPS já atualizados com sucesso, por meio do let's encrypt/certbot (comando utilizado: sudo certbot renew)
Notinha de rodapé: Sempre verificar se o servidor está conectado com a internet antes de rodar esse comando

**Comment by rafalmeida-ifsp** [comment]
Certificado renovado

**Comment by rafalmeida-ifsp** [comment]
``
