### ISSUE TITLE
Ajustar manual para acesso ao Webserver

### ISSUE THREAD

**Issue by rafalmeida-ifsp** [fabsoftwareitp/sitefabrica-jig#67]
Ajustar formatação do manual do Webserver de acordo com as demais páginas (Calendário e Reuniões).
Atualmente tem uma diferença de visualização (tamanho de fonte, por exemplo).

**Comment by Vitor-G-Aquino** [comment]
mudei a extensão do layout, que antes estava com o final ".blog" e os outros estavam com ".projetos".
